#!/usr/bin/env python3
"""Compare what a figure CLAIMS against what the repository actually holds.

Responsibility
    ``make_figures.py --check`` proves a figure matches the generator that
    produced it. ``check_figures.py`` proves no text escapes its box. Neither
    can see whether the figure is **true**, and for two years one of them was
    not: ``aethrion_waves.svg`` rendered *"141 work-package documents"* while
    the registry held 160, and ``aethrion_topology.svg`` said *"221 planning
    files, byte-identical to baseline v1.0.5"* three baselines and 410 files
    later.

    Both regenerated byte-identically every time. That is the whole lesson: a
    deterministic generator reproduces a false claim exactly as faithfully as a
    true one, and a drift check that compares output to generator can only ever
    confirm that the generator has not changed its mind.

The independence rule
    This checker reads the **rendered SVG** and compares it to the **registries**.
    It does not import the figure generators, and it must not: a checker that
    asks the generator what the answer should be is asking the suspect for an
    alibi. Two paths to the same number, meeting at the assertion.

Scope, stated so the passing line is not read as more than it is
    Only claims that are mechanically derivable are checked. A figure can still
    mislabel a relationship, draw the wrong arrow or explain a mechanism
    incorrectly, and nothing here would notice. What this catches is the class
    of defect that actually occurred: a number that was true when it was typed.

Exit codes
    0 — every checked claim matches.  1 — at least one figure says something
    the repository contradicts.
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIGURES = ROOT / "docs" / "figures"
PLAN = ROOT / "planning" / "commissioning"


# ---- registries, read directly and never through a generator ---------------
def registry() -> dict[str, object]:
    matrix = list(csv.DictReader(
        (PLAN / "00_PROGRAM" / "package_dependency_matrix.csv").open(encoding="utf-8")))
    seal = (PLAN / "00_PROGRAM" / "SHA256SUMS.txt").read_text(encoding="utf-8")
    metadata = (PLAN / "00_PROGRAM" / "programme_metadata.json").read_text(encoding="utf-8")
    baseline = re.search(r'"version":\s*"(v[\d.]+)"', metadata).group(1)
    waves = set(re.findall(r'"id":\s*"(W[^"]*)"', metadata))
    scenarios = [p for p in (PLAN / "12_ACCEPTANCE_SCENARIOS").glob("ACC-*.md")
                 if re.match(r"^ACC-\d{2,3}_", p.name)]
    skills = [d for d in (ROOT / "skills").iterdir()
              if d.is_dir() and (d / "SKILL.md").exists()]
    return {
        "packages": len(matrix),
        "wave_ids": waves,
        "numbered_waves": len(waves) - 1,          # the bootstrap wave is named separately
        "sealed": len(seal.strip().splitlines()),
        "baseline": baseline,
        "scenarios": len(scenarios),
        "skills": len(skills),
        "figures": len(list(FIGURES.glob("*.svg"))),
        "wave_members": {w: sum(1 for r in matrix if r["wave_id"] == w) for w in waves},
    }


def rendered_text(path: Path) -> str:
    """The words a reader sees, with the SVG's line breaks flattened."""
    raw = " ".join(re.findall(r">([^<]*)<", path.read_text(encoding="utf-8")))
    return re.sub(r"\s+", " ", raw).strip()


# ---- claims ----------------------------------------------------------------
class Claim:
    """One assertion a figure makes that the repository can adjudicate."""

    def __init__(self, figure: str, pattern: str, fact: str, description: str,
                 cast=int) -> None:
        self.figure, self.pattern = figure, re.compile(pattern)
        self.fact, self.description, self.cast = fact, description, cast

    def check(self, text: str, facts: dict) -> str | None:
        found = self.pattern.search(text)
        if not found:
            return (f"{self.figure}: the {self.description} claim is missing "
                    f"entirely — this checker cannot verify a sentence that is "
                    f"no longer there, so its absence is reported rather than "
                    f"passed over")
        claimed = self.cast(found.group(1))
        actual = facts[self.fact]
        if claimed != actual:
            return (f"{self.figure}: claims {self.description} = {claimed}, "
                    f"the repository holds {actual}")
        return None


CLAIMS = [
    Claim("aethrion_waves.svg", r"(\d+) work-package documents", "packages",
          "total work-package documents"),
    Claim("aethrion_waves.svg", r"work-package documents in (\d+) waves", "numbered_waves",
          "wave count"),
    Claim("aethrion_topology.svg", r"(\d+) planning files", "sealed",
          "sealed planning files"),
    Claim("aethrion_topology.svg", r"baseline (v[\d.]+)", "baseline",
          "commissioning baseline", cast=str),
]


def check_wave_coverage(facts: dict) -> list[str]:
    """Every package in exactly one registered wave, and the bars summing right.

    Exactly-one is true by construction now — wave is a single column — so what
    is worth checking is the pair the construction cannot guarantee: that the
    registry defines every wave used, and that the rendered per-wave bars add
    up to the rendered total rather than to something near it.
    """
    problems = []
    text = rendered_text(FIGURES / "aethrion_waves.svg")
    bars = [int(n) for n in re.findall(r"(\d+) packages?\b", text)]
    total_match = re.search(r"(\d+) work-package documents", text)
    if total_match and bars:
        if sum(bars) != int(total_match.group(1)):
            problems.append(
                f"aethrion_waves.svg: the wave bars sum to {sum(bars)} but the "
                f"figure's own total says {total_match.group(1)} — a reader who "
                f"adds up the rows gets a different answer from the one printed")
        if sum(bars) != facts["packages"]:
            problems.append(
                f"aethrion_waves.svg: the wave bars sum to {sum(bars)}, the "
                f"registry holds {facts['packages']} packages — some package is "
                f"in no wave and therefore in no figure")
    return problems


def check_no_model_consistency() -> list[str]:
    """The figure and its inventory must agree on WHICH rows admit no model.

    They did not: `docs/figures/README.md` said "three gates admit no model at
    all" while the lifecycle figure hatched two. Nothing compared them, because
    a figure's inventory entry is prose and the figure is an SVG.

    The comparison is on the named rows rather than on a number word. The first
    version of this rule matched "two|three|four ... admit no model", and it
    broke the moment the figure started naming the rows instead of counting
    them — a rule that only understands one phrasing reports "cannot compare"
    on an improvement.
    """
    problems = []
    figure = rendered_text(FIGURES / "aethrion_lifecycle.svg")
    inventory = (FIGURES / "README.md").read_text(encoding="utf-8")
    words = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five"}

    stated = re.search(r"([^.]{0,80})admits? no model at all", figure)
    if not stated:
        return ["aethrion_lifecycle.svg no longer states which rows admit no "
                "model — the claim this rule adjudicates has been removed"]
    rows = re.findall(r"\bG\d+[a-b]?(?:·[DE])?\b", stated.group(1))
    if not rows:
        return ["aethrion_lifecycle.svg states a no-model claim that names no "
                "row, so it cannot be checked against the inventory"]

    counted = re.search(r"\b(one|two|three|four|five)\b[^.|\n]{0,60}"
                        r"admits? no model at all", inventory)
    named = [r for r in rows if r in inventory]
    if counted and counted.group(1) != words.get(len(rows)):
        problems.append(
            f"docs/figures/README.md says {counted.group(1)} rows admit no "
            f"model; aethrion_lifecycle.svg names {len(rows)}: "
            f"{', '.join(rows)}")
    elif not counted and len(named) != len(rows):
        problems.append(
            f"docs/figures/README.md does not account for every row the "
            f"lifecycle figure marks no-model: {', '.join(rows)}")
    return problems


def figure_outputs() -> dict[str, str]:
    """Which SVG each generator writes, read from the generator's own source.

    Not inferred from the file name. `fig_evidence.py` writes
    `aethrion_evidence_chain.svg`, and a rule that assumed `fig_X → aethrion_X`
    reported two findings where there was no defect at all — a checker that
    invents a naming convention and then enforces it is worse than none.
    """
    out = {}
    for path in sorted((ROOT / "scripts").glob("fig_*.py")):
        found = re.search(r'"figures"\s*/\s*"([a-z_]+\.svg)"',
                          path.read_text(encoding="utf-8"))
        if found:
            out[path.name] = found.group(1)
    return out


def check_inventory_bijection(facts: dict) -> list[str]:
    """Every generator writes a committed figure; every figure is inventoried."""
    problems = []
    produced = figure_outputs()
    committed = {p.name for p in FIGURES.glob("*.svg")}
    inventory = (FIGURES / "README.md").read_text(encoding="utf-8")

    for generator in sorted(set((ROOT / "scripts").glob("fig_*.py")) -
                            {ROOT / "scripts" / g for g in produced}):
        problems.append(f"scripts/{generator.name} names no output figure")
    for generator, svg in sorted(produced.items()):
        if svg not in committed:
            problems.append(f"scripts/{generator} writes {svg}, which is not committed")
    for svg in sorted(committed - set(produced.values())):
        problems.append(f"{svg} has no generator")
    for svg in sorted(committed):
        if svg not in inventory:
            problems.append(f"{svg} is not listed in docs/figures/README.md")
    return problems


def audit(facts: dict | None = None) -> list[str]:
    facts = facts or registry()
    problems: list[str] = []
    cache: dict[str, str] = {}
    for claim in CLAIMS:
        path = FIGURES / claim.figure
        if not path.exists():
            problems.append(f"{claim.figure} does not exist")
            continue
        cache.setdefault(claim.figure, rendered_text(path))
        result = claim.check(cache[claim.figure], facts)
        if result:
            problems.append(result)
    problems += check_wave_coverage(facts)
    problems += check_no_model_consistency()
    problems += check_inventory_bijection(facts)
    return problems


# ----------------------------------------------------------------- self-test
MUTATIONS = [
    ("a package registry that has grown past what the figure was drawn for",
     lambda f: f.update(packages=f["packages"] + 1)),
    ("a wave added to the registry after the figure was rendered",
     lambda f: f.update(numbered_waves=f["numbered_waves"] + 1)),
    ("a plan seal covering more files than the figure says",
     lambda f: f.update(sealed=f["sealed"] + 7)),
    ("a baseline promoted past the label the figure carries",
     lambda f: f.update(baseline="v9.9.9")),
]


def self_test() -> int:
    """Each mutation is a historical defect. A rule that stays quiet is not a rule."""
    base = registry()
    silent = []
    for description, mutate in MUTATIONS:
        facts = dict(base)
        mutate(facts)
        if not audit(facts):
            silent.append(description)
    print(f"{len(MUTATIONS)} registry mutations injected · "
          f"{len(silent)} produced no finding")
    for description in silent:
        print(f"  ✗ nothing detected {description}")
    if silent:
        return 1
    print("every mutation was caught — the figures are compared to the "
          "repository, not to the code that drew them")
    return 0


def main() -> int:
    if "--self-test" in sys.argv[1:]:
        return self_test()
    facts = registry()
    problems = audit(facts)
    print(f"{facts['figures']} figures · {len(CLAIMS)} derived claims · "
          f"{facts['packages']} packages · {facts['scenarios']} scenarios · "
          f"seal {facts['sealed']} · baseline {facts['baseline']}")
    for problem in problems:
        print(f"  ✗ {problem}")
    if problems:
        print(f"\n{len(problems)} figure(s) claim something the repository contradicts")
        return 1
    print("every mechanically derivable figure claim matches the registries — "
          "which is narrower than \"the figures are correct\", and the number of "
          "claims checked is printed so the gap stays visible")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
