#!/usr/bin/env python3
"""Compare what a figure CLAIMS against what the repository actually holds.

Responsibility
    ``make_figures.py --check`` proves a figure matches the generator that
    produced it. ``check_figures.py`` proves no text escapes its box. Neither
    can see whether the figure is **true**, and for two years one of them was
    not: ``aethrion_waves.svg`` rendered *"141 work-package documents"* while
    the registry held 160, and ``aethrion_topology.svg`` said *"221 planning
    files, byte-identical to baseline v1.0.5"* three baselines and 410 files
    later.

    Both regenerated byte-identically every time. That is the whole lesson: a
    deterministic generator reproduces a false claim exactly as faithfully as a
    true one, and a drift check that compares output to generator can only ever
    confirm that the generator has not changed its mind.

The independence rule
    This checker reads the **rendered SVG** and compares it to the **registries**.
    It does not import the figure generators, and it must not: a checker that
    asks the generator what the answer should be is asking the suspect for an
    alibi. Two paths to the same number, meeting at the assertion.

Scope, stated so the passing line is not read as more than it is
    Only claims that are mechanically derivable are checked. A figure can still
    mislabel a relationship, draw the wrong arrow or explain a mechanism
    incorrectly, and nothing here would notice. What this catches is the class
    of defect that actually occurred: a number that was true when it was typed.

Exit codes
    0 — every checked claim matches.  1 — at least one figure says something
    the repository contradicts.
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIGURES = ROOT / "docs" / "figures"
PLAN = ROOT / "planning" / "commissioning"


# ---- registries, read directly and never through a generator ---------------
def registry() -> dict[str, object]:
    matrix = list(csv.DictReader(
        (PLAN / "00_PROGRAM" / "package_dependency_matrix.csv").open(encoding="utf-8")))
    seal = (PLAN / "00_PROGRAM" / "SHA256SUMS.txt").read_text(encoding="utf-8")
    metadata = (PLAN / "00_PROGRAM" / "programme_metadata.json").read_text(encoding="utf-8")
    baseline = re.search(r'"version":\s*"(v[\d.]+)"', metadata).group(1)
    waves = set(re.findall(r'"id":\s*"(W[^"]*)"', metadata))
    scenarios = [p for p in (PLAN / "12_ACCEPTANCE_SCENARIOS").glob("ACC-*.md")
                 if re.match(r"^ACC-\d{2,3}_", p.name)]
    skills = [d for d in (ROOT / "skills").iterdir()
              if d.is_dir() and (d / "SKILL.md").exists()]
    return {
        "packages": len(matrix),
        "wave_ids": waves,
        "numbered_waves": len(waves) - 1,          # the bootstrap wave is named separately
        "sealed": len(seal.strip().splitlines()),
        "baseline": baseline,
        "scenarios": len(scenarios),
        "skills": len(skills),
        "figures": len(list(FIGURES.glob("*.svg"))),
        "wave_members": {w: sum(1 for r in matrix if r["wave_id"] == w) for w in waves},
    }


def rendered_text(path: Path) -> str:
    """The words a reader sees, with the SVG's line breaks flattened."""
    raw = " ".join(re.findall(r">([^<]*)<", path.read_text(encoding="utf-8")))
    return re.sub(r"\s+", " ", raw).strip()


# ---- claims ----------------------------------------------------------------
class Claim:
    """One assertion a figure makes that the repository can adjudicate."""

    def __init__(self, figure: str, pattern: str, fact: str, description: str,
                 cast=int) -> None:
        self.figure, self.pattern = figure, re.compile(pattern)
        self.fact, self.description, self.cast = fact, description, cast

    def check(self, text: str, facts: dict) -> str | None:
        found = self.pattern.search(text)
        if not found:
            return (f"{self.figure}: the {self.description} claim is missing "
                    f"entirely — this checker cannot verify a sentence that is "
                    f"no longer there, so its absence is reported rather than "
                    f"passed over")
        claimed = self.cast(found.group(1))
        actual = facts[self.fact]
        if claimed != actual:
            return (f"{self.figure}: claims {self.description} = {claimed}, "
                    f"the repository holds {actual}")
        return None


CLAIMS = [
    Claim("aethrion_waves.svg", r"(\d+) work-package documents", "packages",
          "total work-package documents"),
    Claim("aethrion_waves.svg", r"work-package documents in (\d+) waves", "numbered_waves",
          "wave count"),
    Claim("aethrion_topology.svg", r"(\d+) planning files", "sealed",
          "sealed planning files"),
    Claim("aethrion_topology.svg", r"baseline (v[\d.]+)", "baseline",
          "commissioning baseline", cast=str),
]


def check_wave_coverage(facts: dict) -> list[str]:
    """Every package in exactly one registered wave, and the bars summing right.

    Exactly-one is true by construction now — wave is a single column — so what
    is worth checking is the pair the construction cannot guarantee: that the
    registry defines every wave used, and that the rendered per-wave bars add
    up to the rendered total rather than to something near it.
    """
    problems = []
    text = rendered_text(FIGURES / "aethrion_waves.svg")
    bars = [int(n) for n in re.findall(r"(\d+) packages?\b", text)]
    total_match = re.search(r"(\d+) work-package documents", text)
    if total_match and bars:
        if sum(bars) != int(total_match.group(1)):
            problems.append(
                f"aethrion_waves.svg: the wave bars sum to {sum(bars)} but the "
                f"figure's own total says {total_match.group(1)} — a reader who "
                f"adds up the rows gets a different answer from the one printed")
        if sum(bars) != facts["packages"]:
            problems.append(
                f"aethrion_waves.svg: the wave bars sum to {sum(bars)}, the "
                f"registry holds {facts['packages']} packages — some package is "
                f"in no wave and therefore in no figure")
    return problems


def check_no_model_consistency() -> list[str]:
    """The figure and its inventory must agree on WHICH rows admit no model.

    They did not: `docs/figures/README.md` said "three gates admit no model at
    all" while the lifecycle figure hatched two. Nothing compared them, because
    a figure's inventory entry is prose and the figure is an SVG.

    The comparison is on the named rows rather than on a number word. The first
    version of this rule matched "two|three|four ... admit no model", and it
    broke the moment the figure started naming the rows instead of counting
    them — a rule that only understands one phrasing reports "cannot compare"
    on an improvement.
    """
    problems = []
    figure = rendered_text(FIGURES / "aethrion_lifecycle.svg")
    inventory = (FIGURES / "README.md").read_text(encoding="utf-8")
    words = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five"}

    stated = re.search(r"([^.]{0,80})admits? no model at all", figure)
    if not stated:
        return ["aethrion_lifecycle.svg no longer states which rows admit no "
                "model — the claim this rule adjudicates has been removed"]
    rows = re.findall(r"\bG\d+[a-b]?(?:·[DE])?\b", stated.group(1))
    if not rows:
        return ["aethrion_lifecycle.svg states a no-model claim that names no "
                "row, so it cannot be checked against the inventory"]

    counted = re.search(r"\b(one|two|three|four|five)\b[^.|\n]{0,60}"
                        r"admits? no model at all", inventory)
    named = [r for r in rows if r in inventory]
    if counted and counted.group(1) != words.get(len(rows)):
        problems.append(
            f"docs/figures/README.md says {counted.group(1)} rows admit no "
            f"model; aethrion_lifecycle.svg names {len(rows)}: "
            f"{', '.join(rows)}")
    elif not counted and len(named) != len(rows):
        problems.append(
            f"docs/figures/README.md does not account for every row the "
            f"lifecycle figure marks no-model: {', '.join(rows)}")
    return problems


def figure_outputs() -> dict[str, str]:
    """Which SVG each generator writes, read from the generator's own source.

    Not inferred from the file name. `fig_evidence.py` writes
    `aethrion_evidence_chain.svg`, and a rule that assumed `fig_X → aethrion_X`
    reported two findings where there was no defect at all — a checker that
    invents a naming convention and then enforces it is worse than none.
    """
    out = {}
    for path in sorted((ROOT / "scripts").glob("fig_*.py")):
        found = re.search(r'"figures"\s*/\s*"([a-z_]+\.svg)"',
                          path.read_text(encoding="utf-8"))
        if found:
            out[path.name] = found.group(1)
    return out


def check_inventory_bijection(facts: dict) -> list[str]:
    """Every generator writes a committed figure; every figure is inventoried."""
    problems = []
    produced = figure_outputs()
    committed = {p.name for p in FIGURES.glob("*.svg")}
    inventory = (FIGURES / "README.md").read_text(encoding="utf-8")

    for generator in sorted(set((ROOT / "scripts").glob("fig_*.py")) -
                            {ROOT / "scripts" / g for g in produced}):
        problems.append(f"scripts/{generator.name} names no output figure")
    for generator, svg in sorted(produced.items()):
        if svg not in committed:
            problems.append(f"scripts/{generator} writes {svg}, which is not committed")
    for svg in sorted(committed - set(produced.values())):
        problems.append(f"{svg} has no generator")
    for svg in sorted(committed):
        if svg not in inventory:
            problems.append(f"{svg} is not listed in docs/figures/README.md")
    return problems



# ---------------------------------------------------------------------------
# Cross-source claims — added at the visual-completion pass.
#
# The four Claims above compare a rendered NUMBER to a registry. These compare a
# rendered STATEMENT to the decision record or the code it describes, which is
# the class the visual audit actually found:
#
#   two figures named a policy engine that ADR-010 explicitly does not select;
#   one said "nine of the ten links" while the chain marked two as working;
#   one taught a mirror behaviour that finding I10 removed a baseline earlier.
#
# None of these is a count drift. Each is a figure teaching something the
# repository has decided against, which no amount of regenerating fixes.
# ---------------------------------------------------------------------------

POLICY_BACKENDS = ("Cedar", "OPA", "Rego", "Casbin", "Oso")


def check_policy_backend_neutrality() -> list[str]:
    """No figure may name a policy engine while the ADR declines to select one.

    ADR-010 is ACCEPTED and says the bake-off has not run, no policy set is
    authored and no engine is deployed. Two figures named Cedar as the decision
    point anyway — one of them in the box a reader looks at to learn *what
    enforces this*.
    """
    adr = next((p for p in (ROOT / "docs" / "architecture").glob("ADR-010*.md")), None)
    if adr is None:
        return []
    # Whitespace-normalised, because the binding sentence is wrapped and
    # markdown-bolded: `**The bake-off\nhas not run**`. The first version of this
    # guard searched the raw text for a contiguous phrase, found nothing, and
    # concluded the ADR permitted naming an engine — a rule that silently
    # disabled itself on the exact formatting the file happens to use.
    text = re.sub(r"\s+", " ", adr.read_text(encoding="utf-8"))
    binding = ("No document may name a winner" in text
               or "bake-off has not run" in text)
    if not binding:
        return []          # the ADR has been superseded; a backend may now be named
    problems = []
    for path in sorted(FIGURES.glob("*.svg")):
        rendered = rendered_text(path)
        for backend in POLICY_BACKENDS:
            if re.search(rf"\b{backend}\b", rendered):
                problems.append(
                    f"{path.name}: names {backend} while ADR-010 is ACCEPTED and "
                    f"states the bake-off has not run — the commissioned contract "
                    f"is PolicyDecision and the engine behind it is an open, "
                    f"recorded choice")
    return problems


def check_evidence_chain_is_self_consistent() -> list[str]:
    """The hollow count in the caption must equal the links not marked working.

    It did not: the caption said "nine of the ten links" while two carried a
    "working" label, so eight were hollow. A second link became implemented and
    the sentence stayed where it was — understating the system by one, in the
    figure whose entire subject is how much of it exists.

    Both halves are read from the rendered SVG, so this cannot be satisfied by
    the generator agreeing with itself.
    """
    path = FIGURES / "aethrion_evidence_chain.svg"
    if not path.exists():
        return []
    words = {"none": 0, "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
             "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10, "eleven": 11}
    rendered = rendered_text(path)
    stated = re.search(r"(\w+) of the (\w+) links above are still drawn hollow",
                       rendered)
    if not stated:
        return [f"{path.name}: the hollow-link sentence is gone, so this rule can "
                f"no longer adjudicate it"]
    hollow, total = words.get(stated.group(1)), words.get(stated.group(2))
    if hollow is None or total is None:
        return [f"{path.name}: cannot read {stated.group(0)!r} as numbers"]
    working = len(re.findall(r">working<", path.read_text(encoding="utf-8")))
    if hollow + working != total:
        return [f"{path.name}: says {hollow} of {total} links are hollow, and "
                f"{working} carry a 'working' label — {hollow} + {working} "
                f"is not {total}"]
    return []


def check_mirror_description_matches_the_code() -> list[str]:
    """The topology figure may not describe a mirror behaviour the code refuses.

    It said the mirror "overwrites, so the failure mode of editing the vault is
    losing that edit". Finding **I10** had already made `mirror_vault.py` refuse
    to write over any page whose frontmatter says `generated: false` — so the
    figure was teaching a data-loss behaviour that the code had been changed to
    prevent, which is worse than a stale count: a reader avoids using a feature
    that works.
    """
    mirror = ROOT / "scripts" / "mirror_vault.py"
    figure = FIGURES / "aethrion_topology.svg"
    if not (mirror.exists() and figure.exists()):
        return []
    protects = "generated: false" in mirror.read_text(encoding="utf-8")
    rendered = rendered_text(figure)
    if not protects:
        return []
    problems = []
    if re.search(r"never edited back\.", rendered):
        problems.append(
            f"{figure.name}: says the vault is 'never edited back' without "
            f"qualification, while mirror_vault.py protects hand-authored pages")
    if not re.search(r"generated: ?false", rendered):
        problems.append(
            f"{figure.name}: mirror_vault.py refuses to overwrite pages marked "
            f"generated: false, and the figure never says so — a reader is left "
            f"believing any note in the vault is disposable")
    return problems


def audit(facts: dict | None = None) -> list[str]:
    facts = facts or registry()
    problems: list[str] = []
    cache: dict[str, str] = {}
    for claim in CLAIMS:
        path = FIGURES / claim.figure
        if not path.exists():
            problems.append(f"{claim.figure} does not exist")
            continue
        cache.setdefault(claim.figure, rendered_text(path))
        result = claim.check(cache[claim.figure], facts)
        if result:
            problems.append(result)
    problems += check_wave_coverage(facts)
    problems += check_policy_backend_neutrality()
    problems += check_evidence_chain_is_self_consistent()
    problems += check_mirror_description_matches_the_code()
    problems += check_no_model_consistency()
    problems += check_inventory_bijection(facts)
    return problems


# ----------------------------------------------------------------- self-test
MUTATIONS = [
    ("a package registry that has grown past what the figure was drawn for",
     lambda f: f.update(packages=f["packages"] + 1)),
    ("a wave added to the registry after the figure was rendered",
     lambda f: f.update(numbered_waves=f["numbered_waves"] + 1)),
    ("a plan seal covering more files than the figure says",
     lambda f: f.update(sealed=f["sealed"] + 7)),
    ("a baseline promoted past the label the figure carries",
     lambda f: f.update(baseline="v9.9.9")),
]


# Defects planted in the rendered SVG itself. The registry mutations above ask
# "what if the repository moved?"; these ask "what if the figure went stale?" —
# and every one of them is a defect that was actually in the corpus.
FIGURE_MUTATIONS = [
    ("a policy engine named while ADR-010 declines to select one",
     "aethrion_trust.svg", "PolicyDecision contract", "Cedar"),
    ("the same, in the stack figure's execution row",
     "aethrion_stack.svg", "PolicyDecision", "Cedar policy"),
    ("a hollow-link count that no longer matches the working labels",
     "aethrion_evidence_chain.svg", "eight of the ten links", "nine of the ten links"),
    ("a mirror described as wholesale disposable after I10 protected human notes",
     "aethrion_topology.svg",
     "generated pages are replaced, hand-authored ones are protected and never edited back",
     "is never edited back."),
]


def self_test() -> int:
    """Each mutation is a historical defect. A rule that stays quiet is not a rule."""
    base = registry()
    silent = []
    for description, mutate in MUTATIONS:
        facts = dict(base)
        mutate(facts)
        if not audit(facts):
            silent.append(description)

    for description, name, good, bad in FIGURE_MUTATIONS:
        path = FIGURES / name
        original = path.read_text(encoding="utf-8")
        if good not in original:
            silent.append(f"{description} — the mutation anchor is gone, so this "
                          f"defect can no longer be planted")
            continue
        try:
            path.write_text(original.replace(good, bad), encoding="utf-8")
            caught = bool(audit(base))
        finally:
            path.write_text(original, encoding="utf-8")
        if not caught:
            silent.append(description)

    total = len(MUTATIONS) + len(FIGURE_MUTATIONS)
    print(f"{len(MUTATIONS)} registry mutations and {len(FIGURE_MUTATIONS)} "
          f"planted figure defects injected · {len(silent)} produced no finding")
    for description in silent:
        print(f"  ✗ nothing detected {description}")
    if silent:
        return 1
    print("every mutation was caught — the figures are compared to the "
          "repository and to the decisions they describe, not to the code that "
          "drew them")
    return 0


def main() -> int:
    if "--self-test" in sys.argv[1:]:
        return self_test()
    facts = registry()
    problems = audit(facts)
    print(f"{facts['figures']} figures · {len(CLAIMS)} derived claims · "
          f"{facts['packages']} packages · {facts['scenarios']} scenarios · "
          f"seal {facts['sealed']} · baseline {facts['baseline']}")
    for problem in problems:
        print(f"  ✗ {problem}")
    if problems:
        print(f"\n{len(problems)} figure(s) claim something the repository contradicts")
        return 1
    print("every mechanically derivable figure claim matches the registries — "
          "which is narrower than \"the figures are correct\", and the number of "
          "claims checked is printed so the gap stays visible")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
