#!/usr/bin/env python3
"""Answer one question: which work packages can be started right now?

Why this exists
    The plan is 141 packages in a dependency graph. "What do I do next" is a
    graph query, and asking a human to run it by reading 141 documents is how a
    plan stops being used. This computes it.

Where the truth lives
    Dependencies come from the sealed plan, because they are specification.
    **Progress comes from ``delivery/progress.json``, which is deliberately not
    sealed**, because progress is not specification. Recording a day's work must
    not invalidate the integrity proof of the plan the work was against.

What "ready" means here
    Status ``NOT_STARTED`` and every hard dependency ``ACCEPTED``. Not
    ``TECH_COMPLETE`` — the plan's own rule is that issuance is not acceptance,
    so a dependency that has produced something but has not been accepted does
    not release the package that depends on it. This is stricter than it looks
    and it is the point: it is what stops the programme from running ahead of
    its own evidence.

Usage
    python3 scripts/ready_queue.py            regenerate docs/READY.md
    python3 scripts/ready_queue.py --check    fail if it has drifted
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAN = ROOT / "planning" / "commissioning"
# The ledger path is overridable so a test suite never mutates production
# state. It did: `tests/test_progress_cli.py` ran `start WP-011` against the
# real file, and a run that did not reach its restore left WP-011
# `IN_PROGRESS` permanently — after which the test failed on every run and
# the repository's own ready queue was wrong.
LEDGER = Path(os.environ.get("AIRL_PROGRESS_LEDGER",
                             ROOT / "delivery" / "progress.json"))
# The output follows the ledger. When `AIRL_PROGRESS_LEDGER` points somewhere
# else — a test, a what-if — the queue derived from it must not be written over
# the repository's own. It was: the test suite rewrote `docs/READY.md` from a
# temporary ledger, and the verification bundle then reported the queue stale
# on every run that followed a test run.
_LEDGER_OVERRIDDEN = "AIRL_PROGRESS_LEDGER" in os.environ
OUT = Path(os.environ.get(
    "AIRL_READY_QUEUE_OUT",
    (LEDGER.parent / "READY.md") if _LEDGER_OVERRIDDEN else ROOT / "docs" / "READY.md"))

WP_FILE = re.compile(r"^WP-(\d{3})_")
WP_REF = re.compile(r"WP-(\d{3})")
RELEASES = {"ACCEPTED", "INTEGRATED"}


def field(text: str, name: str) -> str:
    match = re.search(rf"^\|\s*{re.escape(name)}\s*\|(.+?)\|\s*$", text, re.M)
    return match.group(1).strip() if match else ""


def load_plan() -> dict[str, dict]:
    packages: dict[str, dict] = {}
    for path in sorted(PLAN.rglob("WP-*.md")):
        if path.name.endswith((".tests.md", ".acceptance.md")):
            continue      # companions carry no header table; the card is the package
        if not WP_FILE.match(path.name):
            continue
        text = path.read_text(encoding="utf-8")
        pid = f"WP-{path.name[3:6]}"
        deps = field(text, "Hard dependencies")
        packages[pid] = {
            "title": text.splitlines()[0].lstrip("# ").strip(),
            "workstream": path.parent.name,
            "owner": field(text, "Accountable owner"),
            "verifier": field(text, "Independent verifier"),
            "effort": (re.search(r"\*\*([SML])\*\*", field(text, "Initial effort class")) or [None, "?"])[1],
            "deps": sorted({f"WP-{d}" for d in WP_REF.findall(deps)} - {pid}),
        }
    return packages


def load_progress() -> dict[str, dict]:
    return json.loads(LEDGER.read_text(encoding="utf-8"))["packages"]


def render(packages: dict[str, dict], progress: dict[str, dict]) -> str:
    def state(pid: str) -> str:
        return progress.get(pid, {}).get("state", "NOT_STARTED")

    ready, blocked, moving, done = [], [], [], []
    for pid, pkg in packages.items():
        st = state(pid)
        if st in RELEASES:
            done.append(pid)
        elif st in ("IN_PROGRESS", "TECH_COMPLETE", "BLOCKED"):
            moving.append(pid)
        else:
            missing = [d for d in pkg["deps"] if state(d) not in RELEASES]
            (blocked if missing else ready).append(pid)
            pkg["missing"] = missing

    lines = [
        "# Ready Queue",
        "",
        "| Field | Value |",
        "|---|---|",
        "| Document type | Generated — what can be started right now |",
        "| Scope | The V1 commissioning programme, as a dependency query |",
        "| Sibling documents | `STATUS.md` (what the checks say) · `V2_CANDIDATES.md` (what is not V1) |",
        "| Status | Generated by `scripts/ready_queue.py`; **never edited by hand** |",
        "| Sources | Dependencies from the sealed plan · progress from `delivery/progress.json`, which is not sealed |",
        "",
        "**In one paragraph.** V1 is the whole commissioning plan, and this page is "
        "the only place that answers *what can I start today*. A package is ready "
        "when nothing it depends on is still unaccepted. `TECH_COMPLETE` does not "
        "release a dependant — issuance is not acceptance — so this queue is "
        "deliberately stricter than a task list and will stay short until the first "
        "package is accepted.",
        "",
        "---",
        "",
        f"## 1. Ready now — {len(ready)}",
        "",
    ]

    if ready:
        lines += ["| Package | Effort | Workstream | Accountable owner | Independent verifier |",
                  "|---|:--:|---|---|---|"]
        for pid in ready:
            p = packages[pid]
            lines.append(f"| **{pid}** — {p['title'].split('—', 1)[-1].strip()} | {p['effort']} | "
                         f"`{p['workstream']}` | {p['owner']} | {p['verifier']} |")
    else:
        lines.append("Nothing. Every remaining package waits on something unaccepted.")

    lines += ["", f"## 2. In flight — {len(moving)}", ""]
    if moving:
        lines += ["| Package | State | Note |", "|---|---|---|"]
        for pid in moving:
            entry = progress.get(pid, {})
            lines.append(f"| **{pid}** | `{entry.get('state')}` | {entry.get('note') or '—'} |")
    else:
        lines.append("Nothing is in progress.")

    lines += ["", f"## 3. Accepted — {len(done)}", "",
              ", ".join(f"`{p}`" for p in done) if done else
              "**None.** No package in this repository has been accepted, which is why "
              "section 1 is as short as it is."]

    lines += ["", f"## 4. Blocked — {len(blocked)}", "",
              "Every entry names the packages it is waiting for, so a blockage is "
              "traceable to a decision rather than to a queue.", ""]
    if blocked:
        lines += ["| Package | Waiting on |", "|---|---|"]
        for pid in blocked:
            miss = packages[pid].get("missing", [])
            shown = ", ".join(f"`{m}`" for m in miss[:6])
            if len(miss) > 6:
                shown += f" (+{len(miss) - 6} more)"
            lines.append(f"| {pid} | {shown} |")

    lines += ["", "---", "", "## 5. Distance to V1", "",
              "V1 is complete when `10_go_live_checklist.md`'s entry conditions hold. "
              "Two of them are countable here; the rest are scenario runs and "
              "rehearsals that cannot be derived from a document.", "",
              "| Condition | Now |", "|---|---|",
              f"| WP-001–119 `COMMISSIONED` | {sum(1 for p in packages if p <= 'WP-119' and p >= 'WP-001' and state(p) == 'INTEGRATED')} of 119 |",
              f"| Packages accepted, all workstreams | {len(done)} of {len(packages)} |",
              "| `PRE_GO_LIVE` scenarios passing on one release candidate | not run |",
              "| Open critical findings | not tracked mechanically yet |",
              "",
              "Update `delivery/progress.json` as work lands, then regenerate this page. "
              "The plan seal is untouched by that, which is the whole reason the ledger "
              "sits outside it.",
              ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    packages = load_plan()
    progress = load_progress()

    unknown = sorted(set(progress) - set(packages))
    orphan = sorted(set(packages) - set(progress))
    if unknown or orphan:
        for pid in unknown:
            print(f"ledger names a package the plan does not have: {pid}", file=sys.stderr)
        for pid in orphan:
            print(f"plan package missing from the ledger: {pid}", file=sys.stderr)
        return 1

    text = render(packages, progress)
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date — run scripts/ready_queue.py")
            return 1
        print(f"ready queue current — {text.count('| **WP-')} package rows")
        return 0

    OUT.write_text(text, encoding="utf-8")
    ready = text.split("## 1. Ready now — ")[1].split("\n")[0]
    print(f"wrote docs/READY.md — {ready} package(s) ready now, "
          f"{len(packages)} in the programme")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
