#!/usr/bin/env python3
"""Generate `docs/STATUS.md` by running the verification bundle.

Responsibility
    Produce the one page that states what is true *now*, from the checkers
    rather than from memory. Dated reports are evidence and are frozen; this
    page is a derived artifact and is regenerated.

Invariant
    Every number here comes from a command that was just run. Nothing is copied
    forward, which is why this file exists: the corpus has twice drifted because
    a count was remembered instead of derived.

Audit findings
    Answers the recurring drift that `check_doc_consistency.py` catches after
    the fact. This removes the opportunity rather than detecting the mistake.

Usage
    uv run python scripts/write_status.py [--check]
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "STATUS.md"

CHECKS = [
    # -q suppresses the summary line when stdout is not a terminal.
    ("Test suite", ["uv", "run", "pytest"], "passed"),
    ("Skill registry", [sys.executable, "scripts/validate_skills.py"], "conform"),
    ("Commissioning plan semantics", [sys.executable, "scripts/validate_commissioning_plan.py"], "OK"),
    ("Workstream indexes", [sys.executable, "scripts/make_plan_indexes.py", "--check"], "drift"),
    ("Declared counts", [sys.executable, "scripts/check_doc_consistency.py"], "agree"),
    ("Stale claims", [sys.executable, "scripts/check_stale_claims.py"], "contradicts the rules above"),
    ("Ready queue", [sys.executable, "scripts/ready_queue.py", "--check"], "ready queue"),
    ("Figures", [sys.executable, "scripts/make_figures.py", "--check"], "drift"),
    ("Figure containment", [sys.executable, "scripts/check_figures.py"], "overflow"),
    ("Reporting register", [sys.executable, "scripts/check_reporting_registry.py"], "auditable"),
]


def run(command: list[str]) -> tuple[bool, str]:
    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True)
    # Some tools split the summary across streams, so both are searched.
    lines = [l.strip() for l in (result.stdout + "\n" + result.stderr).splitlines() if l.strip()]
    # Prefer a line that summarises; pytest's final line is a documentation URL.
    for line in reversed(lines):
        if re.search(r"\b(passed|failed|conform|OK|drift|overflow|auditable|agree|"
                     r"outgrown|inconsisten|stale|contradicts|ready queue)\b", line) and not line.startswith("--"):
            # Strip the elapsed time: a status page that records a duration can
            # never satisfy its own --check, which makes the check worthless.
            return result.returncode == 0, re.sub(r"\s+in \d+\.\d+s\b", "", line)
    return result.returncode == 0, (lines[-1] if lines else "")


def seal() -> tuple[bool, str]:
    plan = ROOT / "planning" / "commissioning"
    result = subprocess.run(["sha256sum", "-c", "00_PROGRAM/SHA256SUMS.txt"],
                            cwd=plan, capture_output=True, text=True)
    ok_lines = [l for l in result.stdout.splitlines() if l.endswith(": OK")]
    total = len((plan / "00_PROGRAM" / "SHA256SUMS.txt").read_text().strip().splitlines())
    return len(ok_lines) == total, f"{len(ok_lines)}/{total} sealed files verified"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the generated page differs from the file on disk")
    args = parser.parse_args()

    rows = []
    all_ok = True
    for name, command, _ in CHECKS:
        ok, line = run(command)
        all_ok &= ok
        rows.append((name, ok, line))
    ok, line = seal()
    all_ok &= ok
    rows.insert(2, ("Commissioning plan seal", ok, line))

    body = [
        "# Current Status",
        "",
        "| Field | Value |",
        "|---|---|",
        "| Document type | Generated status page |",
        "| Scope | What the verification bundle reports **right now** |",
        "| Sibling documents | `review/` holds dated, frozen verification reports |",
        "| Status | Regenerated by `scripts/write_status.py`; **never edited by hand** |",
        f"| Generated | {datetime.now(timezone.utc).isoformat(timespec='seconds')} |",
        "",
        "**In one paragraph.** Every line below is the last line printed by a command "
        "that was just run. Dated reports under `review/` are evidence and stay frozen; "
        "this page is derived and is regenerated, which is how a count stops being "
        "something anyone has to remember.",
        "",
        "## Checks",
        "",
        "| Check | Result |",
        "|---|---|",
    ]
    for name, ok, line in rows:
        body.append(f"| {name} | {'✅' if ok else '❌'} {line} |")

    body += [
        "",
        "## What these checks do not establish",
        "",
        "- **No acceptance.** No work package is `ACCEPTED`; issuance is not acceptance.",
        "- **No behaviour testing.** Skills conform to a format; none has a behaviour baseline.",
        "- **No end-to-end run.** No research question has travelled G0 → G10.",
        "- **No rendering.** No authoring toolchain is installed, so no document has been rendered.",
        "- **Two checks need a live Bridge** (`mcp_smoke`, `acceptance_v0`) and two need the",
        "  operator's vault (the mirrors); they are not run here.",
        "",
    ]
    text = "\n".join(body)

    if args.check:
        current = OUT.read_text() if OUT.is_file() else ""
        # the timestamp always differs; compare everything else
        strip = lambda s: "\n".join(l for l in s.splitlines() if not l.startswith("| Generated |"))
        if strip(current) != strip(text):
            print("docs/STATUS.md is out of date — run scripts/write_status.py")
            return 1
        print("docs/STATUS.md matches the current verification bundle")
        return 0 if all_ok else 1

    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} — {sum(1 for _, ok, _ in rows if ok)}/{len(rows)} checks pass")
    return 0 if all_ok else 1
if __name__ == "__main__":
    raise SystemExit(main())
